// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnm5sEFvwXlLOG3000UwYWFSlTvOd3UuA',
    appId: '1:431075872084:web:05e24f0de4a7b7961fccc1',
    messagingSenderId: '431075872084',
    projectId: 'my-app-11ae0',
    authDomain: 'my-app-11ae0.firebaseapp.com',
    storageBucket: 'my-app-11ae0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnm5sEFvwXlLOG3000UwYWFSlTvOd3UuA',
    appId: '1:431075872084:android:05e24f0de4a7b7961fccc1',
    messagingSenderId: '431075872084',
    projectId: 'my-app-11ae0',
    storageBucket: 'my-app-11ae0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnm5sEFvwXlLOG3000UwYWFSlTvOd3UuA',
    appId: '1:431075872084:ios:05e24f0de4a7b7961fccc1',
    messagingSenderId: '431075872084',
    projectId: 'my-app-11ae0',
    storageBucket: 'my-app-11ae0.firebasestorage.app',
    iosBundleId: 'com.example.oneDay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnm5sEFvwXlLOG3000UwYWFSlTvOd3UuA',
    appId: '1:431075872084:ios:05e24f0de4a7b7961fccc1',
    messagingSenderId: '431075872084',
    projectId: 'my-app-11ae0',
    storageBucket: 'my-app-11ae0.firebasestorage.app',
    iosBundleId: 'com.example.oneDay',
  );
}